FROM ubuntu:18.04

RUN mkdir /app
WORKDIR /app

ENV DEBIAN_FRONTEND noninteractive
ENV DEBCONF_NOWARNINGS yes
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8

COPY docker/requirements.txt /app/requirements.txt

RUN apt-get update && \
    apt-get install python3 python3-pip -y && \
    pip3 install --upgrade pip --no-cache-dir && \
    pip3 install -r /app/requirements.txt --no-cache-dir

RUN apt-get -y install openssh-server && \
    apt-get -y install openssh-client && \
    apt-get -y install sudo && \
    sed -i -e 's/# %wheel\tALL=(ALL)\tNOPASSWD: ALL/%wheel\tALL=(ALL)\tNOPASSWD: ALL/' /etc/sudoers && \
    sed -i -e 's/%wheel\tALL=(ALL)\tALL/# %wheel\tALL=(ALL)\tALL/' /etc/sudoers && \
    visudo -c && \
    echo "root:password" | chpasswd

EXPOSE 5000